//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindbank.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mindbank.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        public static string About_TechUsed {
            get {
                return ResourceManager.GetString("About_TechUsed", resourceCulture);
            }
        }
        
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        public static string About_AboutDesc {
            get {
                return ResourceManager.GetString("About_AboutDesc", resourceCulture);
            }
        }
        
        public static string About_Visit {
            get {
                return ResourceManager.GetString("About_Visit", resourceCulture);
            }
        }
        
        public static string ImportNoteTitle {
            get {
                return ResourceManager.GetString("ImportNoteTitle", resourceCulture);
            }
        }
        
        public static string ImportExportFileType {
            get {
                return ResourceManager.GetString("ImportExportFileType", resourceCulture);
            }
        }
        
        public static string ShowApp {
            get {
                return ResourceManager.GetString("ShowApp", resourceCulture);
            }
        }
        
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        public static string MainView_NewBank {
            get {
                return ResourceManager.GetString("MainView_NewBank", resourceCulture);
            }
        }
        
        public static string MainView_Welcome {
            get {
                return ResourceManager.GetString("MainView_Welcome", resourceCulture);
            }
        }
        
        public static string MainView_CreateNewBank {
            get {
                return ResourceManager.GetString("MainView_CreateNewBank", resourceCulture);
            }
        }
        
        public static string MainView_NewBank_Name {
            get {
                return ResourceManager.GetString("MainView_NewBank_Name", resourceCulture);
            }
        }
        
        public static string MainView_NewBank_Create {
            get {
                return ResourceManager.GetString("MainView_NewBank_Create", resourceCulture);
            }
        }
        
        public static string MainView_ImportFromFile {
            get {
                return ResourceManager.GetString("MainView_ImportFromFile", resourceCulture);
            }
        }
        
        public static string MainView_Import {
            get {
                return ResourceManager.GetString("MainView_Import", resourceCulture);
            }
        }
        
        public static string MainView_Cancel {
            get {
                return ResourceManager.GetString("MainView_Cancel", resourceCulture);
            }
        }
        
        public static string MainView_DeleteBank {
            get {
                return ResourceManager.GetString("MainView_DeleteBank", resourceCulture);
            }
        }
        
        public static string MainView_Yes {
            get {
                return ResourceManager.GetString("MainView_Yes", resourceCulture);
            }
        }
        
        public static string MainView_No {
            get {
                return ResourceManager.GetString("MainView_No", resourceCulture);
            }
        }
        
        public static string NoteScreen_SaveLogToFileTitle {
            get {
                return ResourceManager.GetString("NoteScreen_SaveLogToFileTitle", resourceCulture);
            }
        }
        
        public static string NoteScreen_Loading {
            get {
                return ResourceManager.GetString("NoteScreen_Loading", resourceCulture);
            }
        }
        
        public static string NoteScreen_Close {
            get {
                return ResourceManager.GetString("NoteScreen_Close", resourceCulture);
            }
        }
        
        public static string NoteScreen_SaveLogToFile {
            get {
                return ResourceManager.GetString("NoteScreen_SaveLogToFile", resourceCulture);
            }
        }
        
        public static string NoteScreen_NewTag_Color {
            get {
                return ResourceManager.GetString("NoteScreen_NewTag_Color", resourceCulture);
            }
        }
        
        public static string NoteScreen_NewTag_Add {
            get {
                return ResourceManager.GetString("NoteScreen_NewTag_Add", resourceCulture);
            }
        }
        
        public static string NoteScreen_Random_Max {
            get {
                return ResourceManager.GetString("NoteScreen_Random_Max", resourceCulture);
            }
        }
        
        public static string NoteScreen_Random_Min {
            get {
                return ResourceManager.GetString("NoteScreen_Random_Min", resourceCulture);
            }
        }
        
        public static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        public static string Settings_Main {
            get {
                return ResourceManager.GetString("Settings_Main", resourceCulture);
            }
        }
        
        public static string Settings_HideToTray {
            get {
                return ResourceManager.GetString("Settings_HideToTray", resourceCulture);
            }
        }
        
        public static string Settings_StartInTray {
            get {
                return ResourceManager.GetString("Settings_StartInTray", resourceCulture);
            }
        }
        
        public static string Settings_KeepText {
            get {
                return ResourceManager.GetString("Settings_KeepText", resourceCulture);
            }
        }
        
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        public static string Settings_Theming {
            get {
                return ResourceManager.GetString("Settings_Theming", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDefault {
            get {
                return ResourceManager.GetString("Settings_ThemeDefault", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        public static string Settings_UseBlur {
            get {
                return ResourceManager.GetString("Settings_UseBlur", resourceCulture);
            }
        }
        
        public static string Settings_BlurLevel {
            get {
                return ResourceManager.GetString("Settings_BlurLevel", resourceCulture);
            }
        }
        
        public static string MainView_OK {
            get {
                return ResourceManager.GetString("MainView_OK", resourceCulture);
            }
        }
        
        public static string MainView_CanntoLoad_VersionMismatch {
            get {
                return ResourceManager.GetString("MainView_CanntoLoad_VersionMismatch", resourceCulture);
            }
        }
    }
}
