//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindbank.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mindbank.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        public static string About_TechUsed {
            get {
                return ResourceManager.GetString("About_TechUsed", resourceCulture);
            }
        }
        
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        public static string About_AboutDesc {
            get {
                return ResourceManager.GetString("About_AboutDesc", resourceCulture);
            }
        }
        
        public static string About_Visit {
            get {
                return ResourceManager.GetString("About_Visit", resourceCulture);
            }
        }
        
        public static string ImportNoteTitle {
            get {
                return ResourceManager.GetString("ImportNoteTitle", resourceCulture);
            }
        }
        
        public static string ImportExportFileType {
            get {
                return ResourceManager.GetString("ImportExportFileType", resourceCulture);
            }
        }
        
        public static string ShowApp {
            get {
                return ResourceManager.GetString("ShowApp", resourceCulture);
            }
        }
        
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        public static string MainView_NewBank {
            get {
                return ResourceManager.GetString("MainView_NewBank", resourceCulture);
            }
        }
        
        public static string MainView_Welcome {
            get {
                return ResourceManager.GetString("MainView_Welcome", resourceCulture);
            }
        }
        
        public static string MainView_CreateNewBank {
            get {
                return ResourceManager.GetString("MainView_CreateNewBank", resourceCulture);
            }
        }
        
        public static string MainView_NewBank_Name {
            get {
                return ResourceManager.GetString("MainView_NewBank_Name", resourceCulture);
            }
        }
        
        public static string MainView_NewBank_Create {
            get {
                return ResourceManager.GetString("MainView_NewBank_Create", resourceCulture);
            }
        }
        
        public static string MainView_ImportFromFile {
            get {
                return ResourceManager.GetString("MainView_ImportFromFile", resourceCulture);
            }
        }
        
        public static string MainView_Import {
            get {
                return ResourceManager.GetString("MainView_Import", resourceCulture);
            }
        }
        
        public static string MainView_Cancel {
            get {
                return ResourceManager.GetString("MainView_Cancel", resourceCulture);
            }
        }
        
        public static string MainView_DeleteBank {
            get {
                return ResourceManager.GetString("MainView_DeleteBank", resourceCulture);
            }
        }
        
        public static string MainView_Yes {
            get {
                return ResourceManager.GetString("MainView_Yes", resourceCulture);
            }
        }
        
        public static string MainView_No {
            get {
                return ResourceManager.GetString("MainView_No", resourceCulture);
            }
        }
        
        public static string NoteScreen_SaveLogToFileTitle {
            get {
                return ResourceManager.GetString("NoteScreen_SaveLogToFileTitle", resourceCulture);
            }
        }
        
        public static string NoteScreen_Close {
            get {
                return ResourceManager.GetString("NoteScreen_Close", resourceCulture);
            }
        }
        
        public static string NoteScreen_SaveLogToFile {
            get {
                return ResourceManager.GetString("NoteScreen_SaveLogToFile", resourceCulture);
            }
        }
        
        public static string NoteScreen_NewTag_Color {
            get {
                return ResourceManager.GetString("NoteScreen_NewTag_Color", resourceCulture);
            }
        }
        
        public static string NoteScreen_NewTag_Add {
            get {
                return ResourceManager.GetString("NoteScreen_NewTag_Add", resourceCulture);
            }
        }
        
        public static string NoteScreen_Random_Max {
            get {
                return ResourceManager.GetString("NoteScreen_Random_Max", resourceCulture);
            }
        }
        
        public static string NoteScreen_Random_Min {
            get {
                return ResourceManager.GetString("NoteScreen_Random_Min", resourceCulture);
            }
        }
        
        public static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        public static string Settings_Main {
            get {
                return ResourceManager.GetString("Settings_Main", resourceCulture);
            }
        }
        
        public static string Settings_HideToTray {
            get {
                return ResourceManager.GetString("Settings_HideToTray", resourceCulture);
            }
        }
        
        public static string Settings_StartInTray {
            get {
                return ResourceManager.GetString("Settings_StartInTray", resourceCulture);
            }
        }
        
        public static string Settings_KeepText {
            get {
                return ResourceManager.GetString("Settings_KeepText", resourceCulture);
            }
        }
        
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        public static string Settings_Theming {
            get {
                return ResourceManager.GetString("Settings_Theming", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDefault {
            get {
                return ResourceManager.GetString("Settings_ThemeDefault", resourceCulture);
            }
        }
        
        public static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        public static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        public static string Settings_UseBlur {
            get {
                return ResourceManager.GetString("Settings_UseBlur", resourceCulture);
            }
        }
        
        public static string Settings_BlurLevel {
            get {
                return ResourceManager.GetString("Settings_BlurLevel", resourceCulture);
            }
        }
        
        public static string MainView_OK {
            get {
                return ResourceManager.GetString("MainView_OK", resourceCulture);
            }
        }
        
        public static string MainView_CanntoLoad_VersionMismatch {
            get {
                return ResourceManager.GetString("MainView_CanntoLoad_VersionMismatch", resourceCulture);
            }
        }
        
        public static string Update_CheckForUpdates {
            get {
                return ResourceManager.GetString("Update_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string Update_UpdateAvailable {
            get {
                return ResourceManager.GetString("Update_UpdateAvailable", resourceCulture);
            }
        }
        
        public static string Update_UpToDate {
            get {
                return ResourceManager.GetString("Update_UpToDate", resourceCulture);
            }
        }
        
        public static string Update_1 {
            get {
                return ResourceManager.GetString("Update_1", resourceCulture);
            }
        }
        
        public static string Update_2 {
            get {
                return ResourceManager.GetString("Update_2", resourceCulture);
            }
        }
        
        public static string Update_3 {
            get {
                return ResourceManager.GetString("Update_3", resourceCulture);
            }
        }
        
        public static string Update_4 {
            get {
                return ResourceManager.GetString("Update_4", resourceCulture);
            }
        }
        
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        public static string ToolTip_UpdatesAvailable {
            get {
                return ResourceManager.GetString("ToolTip_UpdatesAvailable", resourceCulture);
            }
        }
        
        public static string ToolTip_CheckingForUpdates {
            get {
                return ResourceManager.GetString("ToolTip_CheckingForUpdates", resourceCulture);
            }
        }
        
        public static string ToolTip_UpToDate {
            get {
                return ResourceManager.GetString("ToolTip_UpToDate", resourceCulture);
            }
        }
        
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
        
        public static string ToolTip_About {
            get {
                return ResourceManager.GetString("ToolTip_About", resourceCulture);
            }
        }
        
        public static string ToolTip_NewNoteGroup {
            get {
                return ResourceManager.GetString("ToolTip_NewNoteGroup", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_EditName {
            get {
                return ResourceManager.GetString("ToolTip_Note_EditName", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SelectItems {
            get {
                return ResourceManager.GetString("ToolTip_Note_SelectItems", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SelectItemsExit {
            get {
                return ResourceManager.GetString("ToolTip_Note_SelectItemsExit", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SelectAll {
            get {
                return ResourceManager.GetString("ToolTip_Note_SelectAll", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_RemoveSelected {
            get {
                return ResourceManager.GetString("ToolTip_Note_RemoveSelected", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_ExportSelected {
            get {
                return ResourceManager.GetString("ToolTip_Note_ExportSelected", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_InvertSelection {
            get {
                return ResourceManager.GetString("ToolTip_Note_InvertSelection", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_Import {
            get {
                return ResourceManager.GetString("ToolTip_Note_Import", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_RandomButton {
            get {
                return ResourceManager.GetString("ToolTip_Note_RandomButton", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_RandomPick {
            get {
                return ResourceManager.GetString("ToolTip_Note_RandomPick", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SearchButton {
            get {
                return ResourceManager.GetString("ToolTip_Note_SearchButton", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SearchUseRegex {
            get {
                return ResourceManager.GetString("ToolTip_Note_SearchUseRegex", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_SearchCaseSensitive {
            get {
                return ResourceManager.GetString("ToolTip_Note_SearchCaseSensitive", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_EditNoteOn {
            get {
                return ResourceManager.GetString("ToolTip_Note_EditNoteOn", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_EditNoteOff {
            get {
                return ResourceManager.GetString("ToolTip_Note_EditNoteOff", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_TagOn {
            get {
                return ResourceManager.GetString("ToolTip_Note_TagOn", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_TagOff {
            get {
                return ResourceManager.GetString("ToolTip_Note_TagOff", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_Send {
            get {
                return ResourceManager.GetString("ToolTip_Note_Send", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_PowerMode {
            get {
                return ResourceManager.GetString("ToolTip_Note_PowerMode", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_PreviewOn {
            get {
                return ResourceManager.GetString("ToolTip_Note_PreviewOn", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_PreviewOff {
            get {
                return ResourceManager.GetString("ToolTip_Note_PreviewOff", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagButton {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagButton", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagOn {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagOn", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagOff {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagOff", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemNewTag {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemNewTag", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagColor {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagColor", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagColorRandom {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagColorRandom", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_NewItemTagAdd {
            get {
                return ResourceManager.GetString("ToolTip_Note_NewItemTagAdd", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_TagMenuButton {
            get {
                return ResourceManager.GetString("ToolTip_Note_TagMenuButton", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_TagMenuTagOn {
            get {
                return ResourceManager.GetString("ToolTip_Note_TagMenuTagOn", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_TagMenuTagOff {
            get {
                return ResourceManager.GetString("ToolTip_Note_TagMenuTagOff", resourceCulture);
            }
        }
        
        public static string ToolTip_Note_Save {
            get {
                return ResourceManager.GetString("ToolTip_Note_Save", resourceCulture);
            }
        }
        
        public static string Tools_IsBitSet_Error {
            get {
                return ResourceManager.GetString("Tools_IsBitSet_Error", resourceCulture);
            }
        }
        
        public static string Tools_GenerateRandomTextError {
            get {
                return ResourceManager.GetString("Tools_GenerateRandomTextError", resourceCulture);
            }
        }
        
        public static string Tools_GenerateRandomTextError2 {
            get {
                return ResourceManager.GetString("Tools_GenerateRandomTextError2", resourceCulture);
            }
        }
    }
}
