name: Build

on:
  workflow_run:
    workflows:
      - devskim
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/Mindbank.Linux/Mindbank.Linux.csproj
      - name: Build
        run: dotnet build --no-restore ./src/Mindbank.Linux/Mindbank.Linux.csproj