name: Mindbank Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup workloads
        run: dotnet workload restore ./Mindbank.sln
      - name: Restore dependencies
        run: dotnet restore ./src/Mindbank.Windows/Mindbank.Windows.csproj
      - name: Build
        run: dotnet build --no-restore ./src/Mindbank.Windows/Mindbank.Windows.csproj
      
      # Windows x64
      - name: Publish (Windows x64)
        run: |
          dotnet publish -c Release -r win-x64 -o ./publish/win-x64/ ./src/Mindbank.Windows/Mindbank.Windows.csproj
          Remove-Item .\publish\win-x64\*.pdb
        shell: pwsh
      - name: Upload Artifact (Windows x64)
        uses: actions/upload-artifact@v4
        with:
          name: Mindbank-Windows-x64
          path: |
            ./publish/win-x64/

      # Windows ARM64
      - name: Publish (Windows ARM64)
        run: |
          dotnet publish -c Release -r win-arm64 -o ./publish/win-arm64/ ./src/Mindbank.Windows/Mindbank.Windows.csproj
          Remove-Item .\publish\win-arm64\*.pdb
        shell: pwsh
      - name: Upload Artifact (Windows ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: Mindbank-Windows-ARM64
          path: |
            ./publish/win-arm64/
